- name: Configure Go Docker
  become: true
  docker_image:
    name: "{{ docker_image }}"
    tag: latest
    force_tag: yes
    repository: "{{ docker_image }}"
    build:
      pull: no
      path: ../go-app
      cache_from:
        - ubuntu:latest
    source: build
  delegate_to: localhost
