- name: Configure Deployment
  become: false
  k8s:
    state: present
    src: ../kubernetes/deployments/application.yaml
    apply: true
    validate:
      fail_on_error: true
  delegate_to: localhost