apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-go
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /neginx
            pathType: Prefix
            backend:
              serviceName: hello-go
              servicePort: 80