- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  delegate_to: localhost

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'snap']
  delegate_to: localhost

- name: Install Snap dependencies
  snap:
    name:
      - kubectl
    classic: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  delegate_to: localhost

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  delegate_to: localhost

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest
  delegate_to: localhost

- name: Install python_docker interpreter
  pip:
    name:
      - docker
      - requests>=2.20.1

- name: Install kubernetes python library
  pip:
    name:
      - openshift >= 0.6
      - PyYAML >= 3.11
      - kubernetes-validate