apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: default
  labels:
    app: go
spec:
  replicas: 10000
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - name: hello-go
          image: evertonfreire/hello-go:latest
          ports:
            - containerPort: 8080